### ISSUE TITLE
Why is numBuckets of type int?

### ISSUE THREAD

**Issue by GeertJohan** [dgryski/go-jump#1]
Hi @dgryski 
I'm wondering, why is the `numBuckets` argument of type `int`?
Why not `int64` right away?
https://github.com/dgryski/go-jump/blob/master/jump.go#L16

**Comment by dgryski** [comment]
Probably so that you can use `len(buckets)` without having an extra conversion.  I remember spending time deciding the types.  In the end it was probably equivalent to a coin-flip.

**Comment by GeertJohan** [comment]
Haha! Thanks :+1:
